### ISSUE TITLE
是否可以支持下能够下载url

### ISSUE THREAD

**Issue by Eric-art-coder** [zzzs/egg-downloader#1]

**Comment by zzzs** [comment]
“下载 url“是指什么？
目前 ctx.downloader(file, name, header) 中 `file` 字段是指文件路径 或者 默认路径：`app/public`

**Comment by Eric-art-coder** [comment]
也就是第三方的资源链接

**Comment by zzzs** [comment]
@guimeisang 抱歉，这个不会支持，与设计初衷偏离了 ：）
